// This file is auto-generated by Payload CMS.
// Run `pnpm types:generate` from the root to update it.
// Do not edit manually.

export interface Config {
  collections: {
    users: User;
    media: Media;
    noticias: Noticia;
    exposiciones: Exposicion;
    miembros: Miembro;
    publicaciones: Publicacion;
    obras: Obra;
    "videos-youtube": VideoYoutube;
  };
  globals: Record<string, never>;
}

export type Locale = "es" | "en" | "fr";

export interface User {
  id: string;
  name: string;
  email: string;
  createdAt: string;
  updatedAt: string;
}

export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Noticia {
  id: string;
  titulo: string;
  slug: string;
  extracto?: string | null;
  contenido?: unknown;
  imagen?: Media | string | null;
  fecha: string;
  categoria?: "actualidad" | "publicaciones" | "eventos" | null;
  createdAt: string;
  updatedAt: string;
}

export interface Exposicion {
  id: string;
  titulo: string;
  slug: string;
  descripcion?: unknown;
  imagenPortada?: Media | string | null;
  galeria?: Array<{
    imagen: Media | string;
    descripcion?: string | null;
    id?: string | null;
  }> | null;
  fechaInicio: string;
  fechaFin?: string | null;
  lugar?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Miembro {
  id: string;
  nombre: string;
  cargo: string;
  bio?: unknown;
  foto?: Media | string | null;
  orden?: number | null;
  redesSociales?: {
    instagram?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
    website?: string | null;
  };
  createdAt: string;
  updatedAt: string;
}

export interface Obra {
  id: string;
  nombre: string;
  año: number;
  imagen?: Media | string | null;
  createdAt: string;
  updatedAt: string;
}

export interface VideoYoutube {
  id: string;
  titulo: string;
  youtubeId: string;
  orden: number;
  createdAt: string;
  updatedAt: string;
}

export interface Publicacion {
  id: string;
  titulo: string;
  slug: string;
  extracto?: string | null;
  imagenPortada?: Media | string | null;
  galeria?: Array<{
    imagen: Media | string;
    id?: string | null;
  }> | null;
  dimensiones?: string | null;
  paginas?: number | null;
  detalleImpresion?: string | null;
  tiendaUrl?: string | null;
  documentalTitulo?: string | null;
  documentalUrl?: string | null;
  orden?: number | null;
  createdAt: string;
  updatedAt: string;
}
